'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Copy, Swords, Shield, Clock3, RotateCcw, Check, Flag, Users } from 'lucide-react';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction,AlertDialogFooter } from './ui/alert-dialog';
import { byId,type Locale } from '../lib/pokemon';
import { gameFetch,type GameRoom,type Profile,ApiError } from '../lib/game-client';
import { gameError } from '../lib/game-copy';
import { availableMoves,active,type BattleEvent } from '../server/battle';
import { PokemonArt,TypeBadge } from './pokemon-visuals';
import { MoveEffect } from './move-effect';
import { Feedback,GameField,GameForm,PendingButton } from './game-ui';
import type { GameController } from './game-hub';
type LobbyRoom={code:string;username:string;createdAt:number};
export function Arena({locale,game,onNav,onPreview}:{locale:Locale;game:GameController;onNav:(v:string)=>void;onPreview:(id:number,trigger:HTMLButtonElement)=>void}){
 const {accept:acceptProfile,refresh:refreshProfile}=game;
 const tr=(ru:string,en:string)=>locale==='ru'?ru:en;
 const [room,setRoom]=useState<GameRoom|null>(null),[rooms,setRooms]=useState<LobbyRoom[]>([]),[roomCode,setRoomCode]=useState<string|null>(null),[joinCode,setJoinCode]=useState(''),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[now,setNow]=useState(()=>Date.now()),[copied,setCopied]=useState(false),[difficulty,setDifficulty]=useState('normal'),[surrender,setSurrender]=useState(false),[effect,setEffect]=useState<BattleEvent|null>(null);
 const sequence=useRef(0),action=useRef(false),controller=useRef<AbortController|null>(null),seen=useRef<Set<string>|null>(null),queue=useRef<BattleEvent[]>([]),mounted=useRef(true);
 const setCode=useCallback((code:string|null)=>{setRoomCode(code);const url=new URL(window.location.href);if(code)url.searchParams.set('room',code);else url.searchParams.delete('room');url.searchParams.delete('join');window.history.replaceState(null,'',url);},[]);
 const accept=useCallback((next:GameRoom|null)=>setRoom(old=>old&&next&&old.code===next.code&&old.version>=next.version?old:next),[]);
 useEffect(()=>{const read=()=>{const p=new URLSearchParams(window.location.search);setRoomCode(p.get('room'));if(p.get('join'))setJoinCode(p.get('join')!.toUpperCase());};read();window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read);},[]);
 const load=useCallback(async()=>{
  await Promise.resolve();
  if(action.current||document.hidden)return;
  controller.current?.abort();const current=new AbortController();controller.current=current;const n=++sequence.current;
  try{
   const result=await gameFetch<{room:GameRoom|null;rooms:LobbyRoom[]}>(`arena${roomCode?`?code=${encodeURIComponent(roomCode)}`:''}`,undefined,current.signal);
   if(!mounted.current||n!==sequence.current)return;
   setRooms(result.rooms);accept(result.room);setError(null);
   if(result.room&&result.room.status!=='finished'&&result.room.status!=='cancelled'&&result.room.deadline<Date.now()){
    const sync=await gameFetch<{room:GameRoom;profile:Profile}>('arena/action',{code:result.room.code,action:'sync'},current.signal);
    if(mounted.current&&n===sequence.current){accept(sync.room);acceptProfile(sync.profile);}
   }
  }catch(e){if(mounted.current&&n===sequence.current&&!(e instanceof DOMException&&e.name==='AbortError'))setError((e as ApiError).code);}
  finally{if(mounted.current&&n===sequence.current)setLoading(false);}
 },[roomCode,accept,acceptProfile]);
 useEffect(()=>{mounted.current=true;const initial=setTimeout(()=>void load(),0);const interval=setInterval(()=>void load(),3000);const visible=()=>{if(!document.hidden)void load();};document.addEventListener('visibilitychange',visible);return()=>{mounted.current=false;clearTimeout(initial);clearInterval(interval);document.removeEventListener('visibilitychange',visible);controller.current?.abort();};},[load]);
 useEffect(()=>{const tick=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(tick);},[]);
 useEffect(()=>{if(room&&!roomCode){const timer=setTimeout(()=>setCode(room.code),0);return()=>clearTimeout(timer);}},[room,roomCode,setCode]);
 useEffect(()=>{if(room?.status==='finished')void refreshProfile();},[room?.status,refreshProfile]);
 useEffect(()=>{
  if(!room)return;
  if(!seen.current){seen.current=new Set(room.logs.map(e=>e.id));return;}
  const fresh=room.logs.filter(e=>!seen.current!.has(e.id));fresh.forEach(e=>seen.current!.add(e.id));queue.current.push(...fresh.filter(e=>e.kind==='attack'||e.kind==='transform'));
  if(!effect&&queue.current.length)setEffect(queue.current.shift()!);
 },[room,effect]);
 const perform=async(path:string,body:unknown)=>{
  if(action.current)return false;action.current=true;controller.current?.abort();++sequence.current;setError(null);
  try{const result=await game.request(path,body);if(result.room){accept(result.room);setCode(result.room.code);}return true;}
  catch(e){setError((e as ApiError).code);return false;}
  finally{action.current=false;}
 };
 const leave=()=>{seen.current=null;queue.current=[];setEffect(null);setRoom(null);setCode(null);setLoading(true);setSurrender(false);};
 const logText=(e:BattleEvent)=>{
  const name=room?.sides[e.actor]?.id==='practice-bot'?tr('Тренировочный бот','Practice bot'):room?.sides[e.actor]?.username||'',mon=e.pokemonId?byId.get(e.pokemonId)?.name[locale]:'';
  if(e.kind==='attack')return `${name} · ${e.move?.name[locale]} ${e.miss?tr('— промах','— missed'):`— ${e.damage} ${tr('урона','damage')}`}${e.effectiveness===0?tr(' · не действует',' · immune'):e.effectiveness&&e.effectiveness>1?tr(' · суперэффективно',' · super effective'):e.effectiveness&&e.effectiveness<1?tr(' · слабый эффект',' · not very effective'):''}`;
  if(e.kind==='switch')return `${name} · ${tr('На поле выходит','Sends out')} ${mon}`;
  if(e.kind==='faint')return `${mon} · ${tr('карточка выбывает','card knocked out')}`;
  if(e.kind==='transform')return `${name} · ${tr('Превращение в','Transforms into')} ${byId.get(e.targetId!)?.name[locale]}`;
  if(e.kind==='pass')return `${name} · ${tr('пропускает ход','passes')}`;
  return tr('Дуэль завершена.','Duel finished.');
 };
 const own=room?.sides[room.you],opponent=room?.sides[1-room.you],fighter=own?active(own):null,moves=fighter?availableMoves(fighter):[],seconds=room?Math.max(0,Math.ceil((room.deadline-now)/1000)):0;
 return <section className='arena-view'><div className='game-heading'><div><span className='eyebrow'>{tr('ПОШАГОВЫЕ ДУЭЛИ · 3 НА 3','TURN-BASED DUELS · 3 VS 3')}</span><h1>{tr('Боевая арена','Battle arena')}</h1></div><button className='outline-button glass' onClick={()=>onNav('collection')}><Shield size={17}/>{tr('Моя команда','My team')}</button></div>
 <Feedback error={error&&error!==game.error?.code?gameError(error,locale):null}>{error&&<button className='text-button' onClick={()=>void load()}><RotateCcw size={15}/>{tr('Повторить','Retry')}</button>}</Feedback>
 {!room?<><div className='lobby-layout'><div className='glass lobby-card'><div className='section-heading'><Swords size={25}/><h2>{tr('Начать дуэль','Start a duel')}</h2></div><p>{tr('Создайте комнату. Другой игрок сможет присоединиться из списка или по вашему коду.','Create a room. Another player can join from the lobby or using your code.')}</p><div className='team-preview'>{game.profile?.team.map(id=><button key={id} onClick={e=>onPreview(id,e.currentTarget)}><PokemonArt id={id} name={byId.get(id)!.name[locale]}/><span>{byId.get(id)!.name[locale]}</span></button>)}</div><PendingButton busy={game.busy} onClick={()=>void perform('arena/create',{})}>{tr('Создать комнату','Create room')}</PendingButton></div>
 <div className='glass lobby-card'><div className='section-heading'><Users size={25}/><h2>{tr('Войти по коду','Join by code')}</h2></div><p>{tr('Попросите другого тренера создать комнату и передать вам код из шести символов.','Ask another trainer to create a room and share its six-character code.')}</p><GameForm busy={game.busy} onSubmit={async()=>{await perform('arena/join',{code:joinCode});}}><GameField label={tr('Код комнаты','Room code')} value={joinCode} onChange={v=>setJoinCode(v.toUpperCase())} autoComplete='off' maxLength={6}/><PendingButton busy={game.busy} disabled={joinCode.length!==6} type='submit'>{tr('Присоединиться','Join room')}</PendingButton></GameForm></div></div>
 <section className='glass lobby-card practice-panel'><div className='section-heading'><Swords size={24}/><h2>{tr('Тренировка с ботом','Practice with a bot')}</h2></div><p>{tr('Три уровня сложности. Бот выбирает ходы на сервере. Тренировки дают опыт и достижения, но не меняют PvP-рейтинг и не начисляют монеты за бой.','Three difficulty levels. Bot orders are server-controlled. Practice earns XP and achievements without affecting PvP rankings or granting battle coins.')}</p><label className='select-label' htmlFor='bot-difficulty'>{tr('Сложность','Difficulty')}</label><select id='bot-difficulty' className='glass-select' value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value='easy'>{tr('Лёгкая','Easy')}</option><option value='normal'>{tr('Обычная','Normal')}</option><option value='hard'>{tr('Сложная','Hard')}</option></select><PendingButton busy={game.busy} onClick={()=>void perform('arena/practice',{difficulty})}>{tr('Начать тренировку','Start practice')}</PendingButton></section>
 <div className='glass open-rooms'><div className='section-heading'><Users size={23}/><h2>{tr('Открытые комнаты','Open rooms')}</h2><button className='text-button' onClick={()=>void load()} aria-label={tr('Обновить комнаты','Refresh rooms')}><RotateCcw size={18}/></button></div>{loading?<p role='status'>{tr('Ищем открытые комнаты…','Finding open rooms…')}</p>:rooms.length?rooms.map(r=><div className='room-row' key={r.code}><span><b>{r.username}</b><small>{r.code}</small></span><PendingButton busy={game.busy} onClick={()=>void perform('arena/join',{code:r.code})}>{tr('Вызвать на бой','Challenge')}</PendingButton></div>):<p>{tr('Пока никто не ждёт соперника. Создайте комнату и поделитесь её кодом.','No one is waiting for an opponent yet. Create a room and share its code.')}</p>}</div></>:room.status==='waiting'?<div className='waiting-room glass'><Clock3 size={35}/><h2>{tr('Ждём второго тренера','Waiting for another trainer')}</h2><p>{room.inviteOnly?tr('Приватная дуэль: приглашение отправлено вашему другу. Только он сможет присоединиться.','Private duel: your friend has been invited. Only they can join.'):tr('Комната видна в общем списке. Передайте код другу или скопируйте ссылку.','Your room is in the lobby. Share the code with a friend or copy the link.')}</p><strong className='room-code'>{room.code}</strong><div className='action-row'><button className='solid-button' onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/?view=arena&join=${room.code}`);setCopied(true);}catch{setCopied(false);}}}><Copy size={16}/>{copied?tr('Ссылка скопирована','Link copied'):tr('Скопировать ссылку','Copy invite link')}</button><PendingButton busy={game.busy} className='outline-button' onClick={()=>void perform('arena/action',{code:room.code,action:'cancel'})}>{tr('Закрыть комнату','Close room')}</PendingButton></div><span className='field-hint'>{tr('Комната закроется через','Room closes in')} {Math.ceil(seconds/60)} {tr('мин.','min.')}</span></div>:room.status==='cancelled'?<div className='waiting-room glass'><Clock3 size={35}/><h2>{room.reason==='expired'?tr('Время ожидания истекло','Waiting time expired'):tr('Комната закрыта','Room closed')}</h2><p>{tr('Создайте новую комнату, когда будете готовы к бою.','Create a new room when you are ready to battle.')}</p><button className='solid-button' onClick={leave}>{tr('Вернуться в лобби','Return to lobby')}</button></div>:<>
 <div className='battle-shell glass'><div className='battle-header'><span>{room.practice&&<b className='practice-badge'>{tr('Тренировка','Practice')}</b>}{tr('Раунд','Round')} <b>{room.status==='finished'?Math.max(1,room.round-1):room.round}</b><small>{room.code}</small></span>{room.status==='active'&&<span className='round-timer'><Clock3 size={17}/>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span>}{room.status==='active'&&<button className='text-button' onClick={()=>setSurrender(true)}><Flag size={16}/>{tr('Сдаться','Surrender')}</button>}</div>
 <div className='battlefield'>{[own,opponent].map((side,i)=>side&&<div className={`battler ${i===0?'my-battler':'opponent-battler'}`} key={side.id}><span className='trainer-name'>{side.id==='practice-bot'?tr('Тренировочный бот','Practice bot'):side.username}{i===0&&<small>{tr('вы','you')}</small>}</span><div className='battle-art-wrap'><PokemonArt id={active(side).formId} name={byId.get(active(side).formId)!.name[locale]} className='battle-art' priority/></div><h2>{byId.get(active(side).formId)!.name[locale]}</h2><div className='hp-line'><span>HP</span><b>{active(side).hp}/{active(side).maxHp}</b></div><div className='hp-track' role='progressbar' aria-label={`${byId.get(active(side).formId)!.name[locale]} HP`} aria-valuemin={0} aria-valuemax={active(side).maxHp} aria-valuenow={active(side).hp}><span style={{width:`${active(side).hp/active(side).maxHp*100}%`}}/></div><div className='battle-reserves'>{side.team.map((p,j)=><span key={j} className={p.hp===0?'knocked-out':j===side.active?'reserve-active':''} title={`${byId.get(p.id)!.name[locale]}: ${p.hp} HP`}><PokemonArt id={p.id} name={`${byId.get(p.id)!.name[locale]} · ${p.hp} HP`}/>{p.hp===0&&<span>×</span>}</span>)}</div></div>)}<span className='versus'>VS</span><MoveEffect move={effect?.move||null} arena direction={effect?.actor===room.you?'right':'left'} onComplete={()=>setEffect(null)}/></div>
 {room.status==='finished'?<div className='battle-result' role='status'><Swords size={25}/><h2>{room.reason==='draw'?tr('Ничья','Draw'):room.winner===game.profile?.id?tr('Победа!','Victory!'):tr('Победа соперника','Opponent wins')}</h2><p>{room.reason==='forfeit'?tr('Один из тренеров завершил дуэль досрочно.','One trainer surrendered.'):tr('Все карточки одной команды выбыли.','One team has been knocked out.')}</p><p>{room.practice?tr('Опыт тренера обновлён. PvP-рейтинг не изменился.','Trainer XP updated. Your PvP rating is unchanged.'):tr('Баланс и статистика обновлены в кабинете.','Your balance and record have been updated.')}</p><button className='solid-button' onClick={leave}>{tr('Новая дуэль','Another duel')}</button></div>:<div className='battle-controls'>
 <div className='turn-status' role='status'>{room.ownOrder?<><Check size={18}/>{tr('Ваш ход принят.','Your order is locked in.')} {room.ownOrder.kind==='attack'?moves[room.ownOrder.index]?.name[locale]:tr('Смена карточки','Card switch')}. {tr('Ждём соперника…','Waiting for your opponent…')}</>:room.opponentReady?tr('Соперник выбрал ход. Теперь ваша очередь.','Your opponent is ready. Choose your order.'):tr('Выберите атаку или смените карточку. Ходы раскрываются одновременно.','Choose an attack or switch cards. Orders are revealed together.')}</div>
 <div className='arena-moves'>{moves.map((move,i)=><button key={move.id} className='arena-move' disabled={game.busy||!!room.ownOrder||(!fighter!.pp.every(p=>p===0)&&fighter!.pp[i]===0)} onClick={()=>void perform('arena/action',{code:room.code,action:'order',round:room.round,order:{kind:'attack',index:i}})}><div><b>{move.name[locale]}</b><TypeBadge type={move.type} locale={locale}/></div><span>{tr('Мощность','Power')} {move.power??(move.id===82?tr("40 урона","40 damage"):tr("переменная","variable"))} · PP {fighter!.pp.every(p=>p===0)?'∞':fighter!.pp[i]}</span></button>)}</div>
 <div className='switch-cards'><span>{tr('Сменить карточку:','Switch card:')}</span>{own?.team.map((p,i)=>i!==own.active&&<button key={i} className='outline-button' disabled={p.hp===0||game.busy||!!room.ownOrder} onClick={()=>void perform('arena/action',{code:room.code,action:'order',round:room.round,order:{kind:'switch',index:i}})}><PokemonArt id={p.id} name={byId.get(p.id)!.name[locale]}/>{byId.get(p.id)!.name[locale]}<small>{p.hp} HP</small></button>)}</div>
 </div>}</div>
 <div className='battle-history glass'><h2>{tr('Ход дуэли','Battle log')}</h2>{room.logs.length?<ol aria-live='polite' aria-relevant='additions'>{room.logs.map(e=><li key={e.id}><small>{e.round}</small><span>{logText(e)}</span></li>)}</ol>:<p>{tr('Команды на поле. Первый раунд начинается.','Teams are on the field. The first round begins.')}</p>}</div></>}
 <details className='arena-rules glass'><summary>{tr('Правила и награды арены','Arena rules and rewards')}</summary><p>{tr('Три разные карточки, сумма базовых характеристик до 1500. Первая выбранная карточка начинает бой. Смена карточки проходит раньше атаки; затем учитываются приоритет и скорость.','Three different cards, with a base stat total of at most 1500. Your first card starts the battle. Switching goes before attacks; move priority and Speed determine the rest.')}</p><p>{tr('Все покемоны играют на 50-м уровне без тренировочных бонусов. Учитываются мощность, точность, физическая или специальная атака, типы, бонус родного типа и PP. Лоу-кик учитывает вес цели, Барахтанье — оставшееся HP, Ярость дракона наносит 40 урона, а Поглощение восстанавливает здоровье. Превращение копирует форму соперника и даёт по 5 PP его атакам; при исчерпании PP доступна Борьба с отдачей. Это упрощённые дуэли: дополнительные статусы и пассивные способности из атласа в расчёт не входят.','All Pokémon battle at level 50 without training bonuses. Power, accuracy, physical or special stats, types, same-type bonus and PP apply. Low Kick uses target weight, Flail uses remaining HP, Dragon Rage deals 40 damage, and Absorb restores HP. Transform copies the opponent’s form with 5 PP per move; depleted PP enables Struggle with recoil. These are simplified duels: secondary status effects and passive atlas abilities are not applied.')}</p><p>{tr('На ход — 120 секунд. Опоздавший игрок пропускает ход; если оба не выбрали ход, дуэль закрывается. Карточка с 0 HP выбывает, следующая выходит автоматически.','Each round lasts 120 seconds. A missing order becomes a pass; if neither player acts, the duel closes. A card with 0 HP is knocked out and the next surviving card enters automatically.')}</p><p>{tr('За первые три результативные дуэли в сутки по UTC: победа +30 монет, поражение +10. За досрочную сдачу до третьего раунда монеты не начисляются. Карточки остаются у владельца.','The first three qualifying duels each UTC day earn 30 coins for a win and 10 for a loss. Surrender before round three awards no coins. You keep your cards.')}</p></details>
 <AlertDialog open={surrender} onOpenChange={v=>{if(!game.busy)setSurrender(v);}}><AlertDialogContent className='game-confirm'><AlertDialogTitle>{tr('Сдаться в этой дуэли?','Surrender this duel?')}</AlertDialogTitle><AlertDialogDescription>{room?.practice?tr('Тренировка завершится. Карточки останутся в коллекции, PvP-рейтинг не изменится.','The practice will end. You keep your cards and your PvP ranking stays unchanged.'):tr('Сопернику будет засчитана победа, вам — поражение. Ваши карточки останутся в коллекции.','Your opponent will receive a win and you will receive a loss. Your cards stay in your collection.')}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={game.busy}>{tr('Продолжить бой','Keep playing')}</AlertDialogCancel><AlertDialogAction disabled={game.busy} className='destructive-button' onClick={e=>{e.preventDefault();if(room)void perform('arena/action',{code:room.code,action:'forfeit'}).then(ok=>{if(ok)setSurrender(false);});}}>{game.busy?tr('Завершаем…','Finishing…'):tr('Сдаться','Surrender')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
