'use client';
import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { Coins, Compass, PackageOpen, Swords, Shield, Check, Eye, EyeOff, Copy, LogOut, UserRound, RotateCcw } from 'lucide-react';
import { pokemon, byId, type Locale } from '../lib/pokemon';
import { type useGame, type Reward, ApiError } from '../lib/game-client';
import { gameError, habitatNames } from '../lib/game-copy';
import { PokemonArt, TypeBadge, types } from './pokemon-visuals';
import { Feedback, GameField, GameForm, PendingButton } from './game-ui';
import { Label } from './ui/label';
import { Arena } from './game-arena';
import { TrainerEditor,TrainerClub } from './trainer-hub';
import { CardReveal } from './card-reveal';
export type GameController=ReturnType<typeof useGame>;
export function GameHub({mode,locale,game,onNav,onPreview}:{mode:string;locale:Locale;game:GameController;onNav:(mode:string)=>void;onPreview:(id:number,trigger:HTMLButtonElement)=>void}){
 const tr=(ru:string,en:string)=>locale==='ru'?ru:en;
 const {profile,busy,loading}=game;
 const [auth,setAuth]=useState('register'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[showPass,setShowPass]=useState(false),[starter,setStarter]=useState(1),[recoveryInput,setRecoveryInput]=useState(''),[invalid,setInvalid]=useState<Record<string,string>>({});
 const [recovery,setRecovery]=useState(''),[copied,setCopied]=useState(false),[teamDraft,setTeamDraft]=useState<{source:string;ids:number[]}|null>(null),[habitat,setHabitat]=useState('forest'),[reward,setReward]=useState<Reward|null>(null),[reveal,setReveal]=useState<Reward|null>(null),[message,setMessage]=useState<{ru:string;en:string}|null>(null);
 const keys=useRef<Record<string,string>>({});
 const teamKey=profile?.team.join(',');
 const source=`${profile?.id||""}:${teamKey||""}`;const team=teamDraft?.source===source?teamDraft.ids:profile?.team||[];
 const setTeam=(value:number[]|((old:number[])=>number[]))=>setTeamDraft({source,ids:typeof value==="function"?value(team):value});
 const [now,setNow]=useState(0);useEffect(()=>{const first=setTimeout(()=>setNow(Date.now()),0),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearTimeout(first);clearInterval(clock);};},[]);
 const attempt=async(fn:()=>Promise<void>)=>{setMessage(null);setInvalid({});try{await fn();}catch(e){if(e instanceof ApiError&&e.field)setInvalid({[e.field]:e.code});}};
 const authenticate=async()=>{
  setInvalid({});
  if(!/^[a-zA-Z0-9_]{3,20}$/.test(username.trim())){setInvalid({username:'username'});return;}
  if(password.length<(auth==='login'?1:10)||password.length>128){setInvalid({password:'password'});return;}
  if(auth==='recover'&&!recoveryInput){setInvalid({recoveryCode:'recovery'});return;}
  await attempt(async()=>{const result=await game.request(`auth/${auth}`,{username,password,starter,recoveryCode:recoveryInput});setPassword('');setRecoveryInput('');if(result.recoveryCode)setRecovery(result.recoveryCode);onNav('collection');});
 };
 const acquire=async(kind:'pack'|'expedition')=>attempt(async()=>{
  keys.current[kind] ||= crypto.randomUUID();
  try{const result=await game.request(kind,{key:keys.current[kind],habitat});setReward(result.reward||null);setReveal(result.reward||null);delete keys.current[kind];}
  catch(e){if(e instanceof ApiError&&!['network','unavailable'].includes(e.code))delete keys.current[kind];throw e;}
 });
 const points=team.reduce((sum,id)=>sum+(byId.get(id)?.stats.reduce((a,b)=>a+b,0)||0),0),dirty=team.join(',')!==teamKey;
 const changeTeam=(id:number)=>setTeam(old=>old.includes(id)?old.filter(x=>x!==id):old.length<3?[...old,id]:old);
 const preview=(id:number,e:React.MouseEvent<HTMLButtonElement>)=>onPreview(id,e.currentTarget);
 const recoveryNotice=recovery?<section className='recovery-notice glass' aria-label={tr('Код восстановления','Recovery code')}><Shield size={25}/><div><h2>{tr('Сохраните код восстановления','Save your recovery code')}</h2><p>{tr('Он поможет вернуть доступ, если забудете пароль. После закрытия код больше не показывается.','Use it to recover your account if you forget your password. The code will not be shown after you dismiss it.')}</p><code>{recovery}</code><div className='action-row'><button className='outline-button' onClick={async()=>{try{await navigator.clipboard.writeText(recovery);setCopied(true);}catch{setCopied(false);}}}><Copy size={16}/>{copied?tr('Скопировано','Copied'):tr('Скопировать','Copy')}</button><button className='solid-button' onClick={()=>{setRecovery('');setCopied(false);}}><Check size={16}/>{tr('Я сохранил код','I saved the code')}</button></div></div></section>:null;
 return <>{reveal&&<CardReveal reward={reveal} locale={locale} onClose={()=>setReveal(null)}/ >}{recoveryNotice}<Feedback error={game.error?gameError(game.error.code,locale):null} message={message?.[locale]}>{game.error&&<button className='text-button' onClick={()=>void game.refresh()}><RotateCcw size={15}/>{tr('Обновить','Refresh')}</button>}</Feedback>{mode==='atlas'?null:loading?<div className='game-loading glass' role='status'>{tr('Загружаем игровой профиль…','Loading your game profile…')}</div>:!profile?<section className='auth-layout'>
 <div className='auth-card glass'><div className='section-heading'><UserRound size={25}/><h1>{tr('Игровой аккаунт','Game account')}</h1></div><div className='auth-tabs' role='group' aria-label={tr('Доступ к аккаунту','Account access')}>{[['register','Регистрация','Register'],['login','Вход','Sign in'],['recover','Восстановление','Recover']].map(([id,ru,en])=><button key={id} aria-pressed={auth===id} onClick={()=>{setAuth(id);setInvalid({});game.clearError();}}>{tr(ru,en)}</button>)}</div>
 <GameForm busy={busy} onSubmit={authenticate}><GameField label={tr('Игровой логин','Game username')} hint={tr('3–20 латинских букв, цифр или _.','3–20 Latin letters, digits or _.')} error={invalid.username?gameError(invalid.username,locale):undefined} value={username} onChange={setUsername} autoComplete='username' maxLength={20}/>
 {auth==='recover'&&<GameField label={tr('Код восстановления','Recovery code')} value={recoveryInput} onChange={setRecoveryInput} autoComplete='off' error={invalid.recoveryCode?gameError(invalid.recoveryCode,locale):undefined}/>}
 <div className='password-control'><GameField label={auth==='recover'?tr('Новый пароль','New password'):tr('Пароль','Password')} hint={auth==='login'?undefined:tr('От 10 до 128 символов.','10–128 characters.')} error={invalid.password?gameError(invalid.password,locale):undefined} type={showPass?'text':'password'} value={password} onChange={setPassword} autoComplete={auth==='login'?'current-password':'new-password'}/><button type='button' className='password-toggle' aria-label={showPass?tr('Скрыть пароль','Hide password'):tr('Показать пароль','Show password')} aria-pressed={showPass} onClick={()=>setShowPass(x=>!x)}>{showPass?<EyeOff size={19}/>:<Eye size={19}/>}</button></div>
 {auth==='register'&&<fieldset className='starter-picker'><legend>{tr('Выберите первого покемона','Choose your first Pokémon')}</legend><div>{[1,4,7].map(id=><button type='button' key={id} aria-pressed={starter===id} onClick={()=>setStarter(id)}><PokemonArt id={id} name={byId.get(id)!.name[locale]}/><span>{byId.get(id)!.name[locale]}</span>{starter===id&&<Check size={16}/>}</button>)}</div><p>{tr('Ещё две разные карточки вы получите сразу после регистрации.','You will receive two more different cards when you register.')}</p></fieldset>}
 <PendingButton busy={busy} type='submit'>{auth==='register'?tr('Создать аккаунт','Create account'):auth==='login'?tr('Войти','Sign in'):tr('Восстановить доступ','Recover account')}</PendingButton></GameForm></div>
 <div className='auth-about glass'><Compass size={30}/><h2>{tr('Ваша коллекция и ваша команда','Your collection and your team')}</h2><p>{tr('Начните с трёх карточек, исследуйте среды обитания и встречайтесь с другими тренерами на арене.','Start with three cards, explore natural habitats and meet other trainers in the arena.')}</p><div className='onboarding-points'><span><Check size={18}/>{tr('Стартовая команда при регистрации','A starter team on registration')}</span><span><Compass size={18}/>{tr('Одна экспедиция каждые 24 часа','One expedition every 24 hours')}</span><span><Swords size={18}/>{tr('Пошаговые бои 3 на 3','Turn-based 3 vs 3 battles')}</span></div></div></section>:mode==='club'?<TrainerClub locale={locale} game={game} onNav={onNav}/>:mode==='account'?<section className='account-view'>
 <div className='game-heading'><div><span className='eyebrow'>{tr('ЛИЧНЫЙ КАБИНЕТ','PLAYER ACCOUNT')}</span><h1>{profile.username}</h1></div><button className='outline-button glass' disabled={busy} onClick={()=>void attempt(async()=>{await game.request('auth/logout',{});setPassword('');setRecovery('');setReward(null);})}><LogOut size={17}/>{tr('Выйти','Sign out')}</button></div>
 <div className='profile-stats'><div className='glass'><Coins/><b>{profile.credits}</b><span>{tr('Монет','Coins')}</span></div><div className='glass'><PackageOpen/><b>{profile.cards.length}</b><span>{tr('Карточек','Cards')}</span></div><div className='glass'><Swords/><b>{profile.wins} / {profile.losses}</b><span>{tr('Побед / поражений','Wins / losses')}</span></div></div>
 <div className='account-columns'><div className='glass account-panel'><h2>{tr('Боевая команда','Battle team')}</h2><div className='team-preview'>{profile.team.map(id=><button key={id} onClick={e=>preview(id,e)}><PokemonArt id={id} name={byId.get(id)!.name[locale]}/><span>{byId.get(id)!.name[locale]}</span></button>)}</div><div className='action-row'><button className='outline-button' onClick={()=>onNav('collection')}>{tr('Изменить команду','Edit team')}</button><button className='solid-button' onClick={()=>onNav('arena')}><Swords size={16}/>{tr('На арену','Enter arena')}</button></div></div><div className='glass account-panel'><h2>{tr('Восстановление аккаунта','Account recovery')}</h2><p>{tr('Если потеряли сохранённый код, создайте новый, подтвердив пароль. Предыдущий код перестанет действовать.','If you lost your saved code, generate a new one by confirming your password. The previous code will expire.')}</p><GameForm busy={busy} onSubmit={()=>attempt(async()=>{const result=await game.request('auth/recovery-code',{password});setPassword('');setRecovery(result.recoveryCode||'');})}><GameField label={tr('Текущий пароль','Current password')} type='password' autoComplete='current-password' value={password} onChange={setPassword} error={invalid.password?gameError(invalid.password,locale):undefined}/><PendingButton busy={busy} type='submit'>{tr('Создать новый код','Generate new code')}</PendingButton></GameForm></div></div><TrainerEditor key={profile.id} locale={locale} game={game} onPreview={onPreview}/></section>:mode==='arena'?<Arena locale={locale} game={game} onNav={onNav} onPreview={onPreview}/>:<section className='collection-view'>
 <div className='game-heading'><div><span className='eyebrow'>{tr('КОЛЛЕКЦИЯ ТРЕНЕРА','TRAINER COLLECTION')}</span><h1>{tr('Мои карточки','My cards')} <span>{profile.cards.length}</span></h1></div><span className='coin-balance glass'><Coins size={21}/><b>{profile.credits}</b>{tr('монет','coins')}</span></div>
 <div className='acquisition-grid'><div className='acquisition-card glass'><div className='section-heading'><Compass size={24}/><h2>{tr('Ежедневная экспедиция','Daily expedition')}</h2></div><p>{tr('Найдите покемона в выбранной среде. Повторная карточка приносит 20 монет.','Discover a Pokémon in your chosen habitat. A duplicate earns 20 coins.')}</p><div className='expedition-controls'><div><Label htmlFor='expedition-habitat'>{tr('Среда обитания','Habitat')}</Label><select id='expedition-habitat' value={habitat} onChange={e=>setHabitat(e.target.value)}>{Object.entries(habitatNames).filter(([id])=>pokemon.some(p=>p.habitat===id&&!p.isLegendary&&!p.isMythical)).map(([id,n])=><option key={id} value={id}>{n[locale==='ru'?0:1]}</option>)}</select></div><PendingButton busy={busy} disabled={profile.expeditionAt>now-86400000} onClick={()=>void acquire('expedition')}>{tr('Отправиться','Explore')}</PendingButton></div>{profile.expeditionAt>now-86400000&&<span className='field-hint'>{tr('Следующая экспедиция: ','Next expedition: ')}{new Date(profile.expeditionAt+86400000).toLocaleString(locale==='ru'?'ru-RU':'en-GB',{dateStyle:'short',timeStyle:'short'})}</span>}</div>
 <div className='acquisition-card glass'><div className='section-heading'><PackageOpen size={24}/><h2>{tr('Набор исследователя','Explorer pack')}</h2></div><p>{tr('Одна карточка за 100 игровых монет. Монеты зарабатываются в боях и за повторные карточки.','One card for 100 game coins. Earn coins in battles and from duplicate cards.')}</p><span className='pack-odds'>{tr('Обычная 90% · эволюция 9% · легендарная или мифическая 1%. Повтор: +20 монет.','Common 90% · evolved 9% · legendary or mythical 1%. Duplicate: +20 coins.')}</span><PendingButton busy={busy} disabled={profile.credits<100} onClick={()=>void acquire('pack')}><Coins size={16}/>{tr('Открыть за 100','Open for 100')}</PendingButton></div></div>
 {reward&&<div className='reward-card glass' role='status'><PokemonArt id={reward.pokemonId} name={byId.get(reward.pokemonId)!.name[locale]}/><div><span className='micro-label'>{reward.duplicate?tr('ПОВТОРНАЯ КАРТОЧКА','DUPLICATE CARD'):tr('НОВАЯ КАРТОЧКА','NEW CARD')}</span><h2>{byId.get(reward.pokemonId)!.name[locale]}</h2><p>{reward.duplicate?tr('+20 монет в копилку.','+20 coins in your balance.'):tr('Уже в вашей коллекции. Можно добавить в команду.','Added to your collection. You can select it for your team.')}</p></div><button className='outline-button' onClick={e=>preview(reward.pokemonId,e)}>{tr('Посмотреть','View card')}</button></div>}
 <div className='team-dock glass'><div><h2><Shield size={21}/>{tr('Боевая команда','Battle team')} <span>{team.length}/3</span></h2><p>{tr('Уберите карточку из команды, чтобы выбрать другую. Первой в бой выходит карточка №1.','Remove a team card to choose another. Card #1 enters the battle first.')}</p><span className={points>1500?'field-error':'field-hint'}>{tr('Сумма характеристик: ','Base stat total: ')}{points}/1500</span></div><div className='team-slots'>{[0,1,2].map(i=><span key={i}>{team[i]?<><PokemonArt id={team[i]} name={byId.get(team[i])!.name[locale]}/><small>{i+1}</small></>:<b>{i+1}</b>}</span>)}</div><div className='team-save'><PendingButton busy={busy} disabled={!dirty||team.length!==3||points>1500} onClick={()=>void attempt(async()=>{await game.request('team',{team});setMessage({ru:'Команда сохранена.',en:'Team saved.'});})}>{tr('Сохранить команду','Save team')}</PendingButton>{dirty&&<button className='text-button' onClick={()=>setTeam(profile.team)}>{tr('Отменить изменения','Discard changes')}</button>}</div></div>
 <div className='owned-grid'>{profile.cards.map(card=>{const p=byId.get(card.id)!;const picked=team.indexOf(card.id);return <div className='owned-card glass' key={card.id} style={{'--pokemon-color':types[p.types[0]].color} as CSSProperties}><button className='owned-preview' onClick={e=>preview(card.id,e)}><span className='pokedex-number'>#{String(card.id).padStart(3,'0')}</span><PokemonArt id={card.id} name={p.name[locale]}/><h3>{p.name[locale]}</h3></button><div className='badge-row'>{p.types.map(t=><TypeBadge key={t} type={t} locale={locale}/>)}</div><button className={`team-select ${picked>=0?'selected':''}`} disabled={picked<0&&team.length===3} aria-pressed={picked>=0} onClick={()=>changeTeam(card.id)}>{picked>=0?<><Check size={16}/>{tr('В команде','In team')} · {picked+1}</>:tr('В команду','Add to team')}</button>{p.evolution.edges.filter(edge=>edge.from===card.id).map(edge=><PendingButton key={edge.to} className='evolve-button outline-button' busy={busy} disabled={profile.credits<150||profile.cards.some(c=>c.id===edge.to)} onClick={()=>void attempt(async()=>{const key=keys.current[`evolve-${edge.to}`] ||= crypto.randomUUID();const result=await game.request('evolve',{from:card.id,to:edge.to,key});setReward(result.reward||null);setReveal(result.reward||null);delete keys.current[`evolve-${edge.to}`];})}>{profile.cards.some(c=>c.id===edge.to)?tr('Форма получена','Form collected'):`${tr('Развить','Evolve')} → ${byId.get(edge.to)!.name[locale]} · 150`}</PendingButton>)}</div>;})}</div><p className='collection-evo-note glass'>{tr('Игровое развитие стоит 150 монет. Новая форма добавляется в коллекцию, исходная карточка остаётся. Условия эволюции в атласе относятся к оригинальным играм.','Game evolution costs 150 coins. The new form joins your collection and you keep the original card. Atlas evolution conditions refer to the original games.')}</p></section>}</>;
}
