"use client";
import {useState,type CSSProperties} from "react";
import {Bolt,Flame,Droplets,Leaf,Mountain,CircleDot,Sparkles,Swords,Wind,Bug,Ghost,Snowflake,Flower2,Shield,CircleHelp,Gem} from "lucide-react";
import type {Locale,Localized} from "../lib/pokemon";
export const types:Record<string,{name:Localized;color:string;icon:typeof Leaf}>={
 grass:{name:{ru:"Травяной",en:"Grass"},color:"#438457",icon:Leaf},poison:{name:{ru:"Ядовитый",en:"Poison"},color:"#9267ad",icon:Droplets},fire:{name:{ru:"Огненный",en:"Fire"},color:"#c16436",icon:Flame},water:{name:{ru:"Водный",en:"Water"},color:"#3979b4",icon:Droplets},electric:{name:{ru:"Электрический",en:"Electric"},color:"#9b7316",icon:Bolt},normal:{name:{ru:"Обычный",en:"Normal"},color:"#6d786f",icon:CircleDot},flying:{name:{ru:"Летающий",en:"Flying"},color:"#578fa0",icon:Wind},bug:{name:{ru:"Насекомый",en:"Bug"},color:"#6c8328",icon:Bug},ground:{name:{ru:"Земляной",en:"Ground"},color:"#997143",icon:Mountain},rock:{name:{ru:"Каменный",en:"Rock"},color:"#8e7a46",icon:Gem},fairy:{name:{ru:"Волшебный",en:"Fairy"},color:"#b76287",icon:Flower2},psychic:{name:{ru:"Психический",en:"Psychic"},color:"#b35683",icon:Sparkles},fighting:{name:{ru:"Боевой",en:"Fighting"},color:"#b1624c",icon:Swords},steel:{name:{ru:"Стальной",en:"Steel"},color:"#6a8190",icon:Shield},ghost:{name:{ru:"Призрачный",en:"Ghost"},color:"#72669f",icon:Ghost},ice:{name:{ru:"Ледяной",en:"Ice"},color:"#398e9e",icon:Snowflake},dragon:{name:{ru:"Драконий",en:"Dragon"},color:"#637ab6",icon:Flame},dark:{name:{ru:"Тёмный",en:"Dark"},color:"#655871",icon:Ghost}};
export function TypeBadge({type,locale}:{type:string;locale:Locale}){const t=types[type];if(!t)return null;const Icon=t.icon;return <span className="type-badge" style={{"--type-color":t.color} as CSSProperties}><Icon size={13} aria-hidden="true"/><span>{t.name[locale]}</span></span>}
// Bundled, pre-sized WebP portraits need no runtime image optimization service.
// eslint-disable-next-line @next/next/no-img-element
export function PokemonArt({id,name,className="",priority=false}:{id:number;name:string;className?:string;priority?:boolean}){const [failed,setFailed]=useState<number|null>(null);return failed===id?<div className={`art-fallback ${className}`} role="img" aria-label={name}><CircleHelp size={48}/><span>{name}</span></div>:<img className={className} src={`/pokemon/${id}.webp`} width="475" height="475" alt={name} loading={priority?"eager":"lazy"} decoding="async" onError={()=>setFailed(id)}/>}
