'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Trophy,Star,Users,Check,RotateCcw,UserRound,Coins } from 'lucide-react';
import { byId,type Locale } from '../lib/pokemon';
import { gameFetch,ApiError,type GameRoom } from '../lib/game-client';
import { gameError,habitatNames } from '../lib/game-copy';
import type { GameController } from './game-hub';
import { PokemonArt } from './pokemon-visuals';
import { GameField,GameForm,PendingButton,Feedback } from './game-ui';
type Task={id:string;name:string;done:boolean;claimed:boolean;coins:number;xp:number;daily:boolean};
type Friend={id:string;username:string;avatar:number;status:string;requester:string};
type ClubData={tasks:Task[];friends:Friend[];invites:{id:string;code:string;username:string}[];ranking:{season:{id:string;endsAt:number};players:{id:string;username:string;avatar:number;wins:number;losses:number;points:number;rank:number;league:string}[]};seasonReward:{id:string;coins:number;claimed:boolean}};
const taskNames:Record<string,[string,string]>={explore:['Отправиться в экспедицию','Go on an expedition'],duel:['Завершить бой с игроком','Finish a player duel'],practice:['Победить тренировочного бота','Defeat the practice bot'],collector:['Собрать 10 карточек','Collect 10 cards'],winner:['Одержать первую PvP-победу','Win your first PvP duel'],veteran:['Одержать 10 PvP-побед','Win 10 PvP duels'],evolve:['Развить первую карточку','Evolve your first card'],botmaster:['Победить бота 3 раза','Defeat the bot 3 times']};
const leagues:Record<string,[string,string]>={bronze:['Бронза','Bronze'],silver:['Серебро','Silver'],gold:['Золото','Gold'],legend:['Легенда','Legend']};
export function TrainerEditor({locale,game,onPreview}:{locale:Locale;game:GameController;onPreview:(id:number,trigger:HTMLButtonElement)=>void}){
 const p=game.profile!;const tr=(ru:string,en:string)=>locale==='ru'?ru:en;
 const [avatar,setAvatar]=useState(p.trainer.avatar),[cover,setCover]=useState(p.trainer.cover),[favorites,setFavorites]=useState(p.trainer.favorites),[saved,setSaved]=useState(false);
 const dirty=avatar!==p.trainer.avatar||cover!==p.trainer.cover||favorites.join(',')!==p.trainer.favorites.join(',');
 useEffect(()=>{window.dispatchEvent(new CustomEvent('pokehabitat:dirty',{detail:dirty}));const guard=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>{window.dispatchEvent(new CustomEvent('pokehabitat:dirty',{detail:false}));window.removeEventListener('beforeunload',guard);};},[dirty]);
 const toggle=(id:number)=>{setSaved(false);setFavorites(old=>old.includes(id)?old.filter(x=>x!==id):old.length<3?[...old,id]:old);};
 return <section className='trainer-customization glass account-panel'><div className={`trainer-cover cover-${p.trainer.cover}`}><PokemonArt id={p.trainer.avatar} name={tr('Аватар тренера','Trainer avatar')} className='trainer-avatar'/><div><span className='micro-label'>{tr('ТРЕНЕР','TRAINER')}</span><h2>{p.username}</h2><p>{tr('Уровень','Level')} {p.trainer.level} · {p.trainer.xp} XP</p><div className='xp-track' role='progressbar' aria-label={tr('Опыт до следующего уровня','Experience to the next level')} aria-valuemin={0} aria-valuemax={100} aria-valuenow={p.trainer.xp%100}><span style={{width:`${p.trainer.xp%100}%`}}/></div><small>{100-p.trainer.xp%100} XP {tr('до следующего уровня','to next level')}</small></div></div>
 <div className='favorite-showcase'>{p.trainer.favorites.length?p.trainer.favorites.map(id=><button key={id} onClick={e=>onPreview(id,e.currentTarget)}><PokemonArt id={id} name={byId.get(id)!.name[locale]}/><span>{byId.get(id)!.name[locale]}</span></button>):<p>{tr('Выберите любимых покемонов для витрины профиля.','Choose favorite Pokémon for your profile showcase.')}</p>}</div>
 <h3>{tr('Персонализация профиля','Customize your profile')}</h3><p className='field-hint'>{tr('Аватар и до трёх любимых покемонов — из вашей коллекции.','Choose your avatar and up to three favorites from your collection.')}</p>
 <div className='profile-picker' role='group' aria-label={tr('Аватар','Avatar')}>{p.cards.map(c=><button key={c.id} aria-pressed={avatar===c.id} aria-label={byId.get(c.id)!.name[locale]} onClick={()=>{setAvatar(c.id);setSaved(false);}}><PokemonArt id={c.id} name={byId.get(c.id)!.name[locale]}/>{avatar===c.id&&<Check size={16}/>}</button>)}</div>
 <label className='select-label' htmlFor='profile-cover'>{tr('Обложка','Cover')}</label><select id='profile-cover' className='glass-select' value={cover} onChange={e=>{setCover(e.target.value);setSaved(false);}}>{Object.entries(habitatNames).map(([id,name])=><option key={id} value={id}>{name[locale==='ru'?0:1]}</option>)}</select>
 <div className='favorites-picker' role='group' aria-label={tr('Любимые покемоны','Favorite Pokémon')}>{p.cards.map(c=><button key={c.id} className='outline-button' aria-pressed={favorites.includes(c.id)} disabled={!favorites.includes(c.id)&&favorites.length>=3} onClick={()=>toggle(c.id)}><Star size={14} fill={favorites.includes(c.id)?'currentColor':'none'}/>{byId.get(c.id)!.name[locale]}</button>)}</div>
 <div className='action-row'><PendingButton busy={game.busy} disabled={!dirty} onClick={()=>void game.request('trainer',{avatar,cover,favorites}).then(()=>setSaved(true)).catch(()=>{})}>{tr('Сохранить профиль','Save profile')}</PendingButton>{dirty&&<button className='text-button' onClick={()=>{setAvatar(p.trainer.avatar);setCover(p.trainer.cover);setFavorites(p.trainer.favorites);setSaved(false);}}>{tr('Отменить изменения','Discard changes')}</button>}</div>{saved&&<p className='field-hint' role='status'>{tr('Оформление профиля сохранено.','Profile appearance saved.')}</p>}
 </section>;
}
export function TrainerClub({locale,game,onNav}:{locale:Locale;game:GameController;onNav:(v:string)=>void}){
 const tr=(ru:string,en:string)=>locale==='ru'?ru:en,p=game.profile!;
 const [data,setData]=useState<ClubData|null>(null),[error,setError]=useState<string|null>(null),[username,setUsername]=useState(''),[message,setMessage]=useState<string|null>(null);
 const sequence=useRef(0),controller=useRef<AbortController|null>(null),mounted=useRef(true);
 const load=useCallback(async()=>{if(document.hidden)return;controller.current?.abort();const abort=new AbortController();controller.current=abort;const n=++sequence.current;try{const result=await gameFetch<ClubData>('club',undefined,abort.signal);if(mounted.current&&n===sequence.current){setData(result);setError(null);}}catch(e){if(mounted.current&&n===sequence.current&&!(e instanceof DOMException&&e.name==='AbortError'))setError((e as ApiError).code);}},[]);
 useEffect(()=>{mounted.current=true;const first=setTimeout(()=>void load(),0),interval=setInterval(()=>void load(),10000);return()=>{mounted.current=false;clearTimeout(first);clearInterval(interval);controller.current?.abort();};},[load]);
 const act=async(path:string,body:unknown)=>{setMessage(null);try{const result=await game.request(path,body);if(result.room){const u=new URL(window.location.href);u.searchParams.set('room',(result.room as GameRoom).code);window.history.replaceState(null,'',u);onNav('arena');}else{await load();setMessage(tr('Готово. Данные обновлены.','Done. Your data is updated.'));}return true;}catch{return false;}};
 return <section className='trainer-club'><div className='game-heading'><div><span className='eyebrow'>{tr('ЗАДАНИЯ · РЕЙТИНГ · ДРУЗЬЯ','QUESTS · RANKING · FRIENDS')}</span><h1>{tr('Клуб тренеров','Trainer club')}</h1></div><span className='coin-balance glass'><Star size={18}/>{tr('Уровень','Level')} {p.trainer.level}</span></div>
 <Feedback error={error?gameError(error,locale):null} message={message}>{error&&<button className='text-button' onClick={()=>void load()}><RotateCcw size={15}/>{tr('Повторить','Retry')}</button>}</Feedback>
 {!data?<div className='game-loading glass' role='status'>{error?tr('Не удалось загрузить клуб.','Could not load the club.'):tr('Загружаем клуб…','Loading the club…')}</div>:<>
 <div className='club-columns'><section className='glass account-panel'><div className='section-heading'><Star size={23}/><h2>{tr('Задания и достижения','Quests and achievements')}</h2></div><p className='field-hint'>{tr('Ежедневные задания обновляются в 00:00 UTC. Опыт повышает уровень тренера и не усиливает карточки.','Daily quests reset at 00:00 UTC. XP raises your trainer level without boosting card stats.')}</p>{[true,false].map(daily=><div className='quest-group' key={String(daily)}><h3>{daily?tr('Сегодня','Today'):tr('Достижения','Achievements')}</h3>{data.tasks.filter(t=>t.daily===daily).map(t=><div className={`quest-row ${t.claimed?'quest-claimed':''}`} key={t.id}><div><b>{taskNames[t.name]?.[locale==='ru'?0:1]}</b><span><Coins size={13}/>{t.coins} · {t.xp} XP</span></div><PendingButton busy={game.busy} disabled={!t.done||t.claimed} onClick={()=>void act('task/claim',{id:t.id})}>{t.claimed?<><Check size={15}/>{tr('Получено','Claimed')}</>:t.done?tr('Получить','Claim reward'):tr('В процессе','In progress')}</PendingButton></div>)}</div>)}</section>
 <section className='glass account-panel'><div className='section-heading'><Trophy size={23}/><h2>{tr('Сезонный рейтинг','Season ranking')}</h2></div><p className='field-hint'>{tr('Сезон','Season')} {data.ranking.season.id} · {tr('До','Until')} {new Date(data.ranking.season.endsAt).toLocaleDateString(locale==='ru'?'ru-RU':'en-GB',{timeZone:'UTC'})}</p><p className='field-hint'>{tr('PvP: +25 за победу, −10 за поражение, минимум 0. Бронза → Серебро (100) → Золото (250) → Легенда (500).','PvP: +25 per win, −10 per loss, floor 0. Bronze → Silver (100) → Gold (250) → Legend (500).')}</p>
 <p className='field-hint'>{tr('Награды прошлого сезона: 1-е место — 300 монет, 2–3-е — 200, 4–10-е — 100. Нужно больше 0 очков.','Previous season rewards: rank 1 gets 300 coins, ranks 2–3 get 200, ranks 4–10 get 100. A positive score is required.')}</p>
 {data.seasonReward.coins>0&&<div className='season-reward'><span>{data.seasonReward.id}: +{data.seasonReward.coins} {tr('монет','coins')}</span><PendingButton busy={game.busy} disabled={data.seasonReward.claimed} onClick={()=>void act('season/claim',{})}>{data.seasonReward.claimed?tr('Получено','Claimed'):tr('Получить награду','Claim reward')}</PendingButton></div>}
 {data.ranking.players.length?<ol className='rank-list'>{data.ranking.players.map(r=><li key={r.id} className={r.id===p.id?'my-rank':''}><b>{r.rank}</b><PokemonArt id={r.avatar} name={r.username}/><div><strong>{r.username}</strong><span>{leagues[r.league][locale==='ru'?0:1]} · {r.wins}/{r.losses} {tr('П/П','W/L')}</span></div><b>{r.points}</b></li>)}</ol>:<div className='club-empty'><Trophy size={32}/><p>{tr('Сезон только начинается. Сыграйте первую дуэль с тренером.','The season is just beginning. Play your first trainer duel.')}</p><button className='outline-button' onClick={()=>onNav('arena')}>{tr('На арену','Enter arena')}</button></div>}</section></div>
 <section className='glass account-panel friends-panel'><div className='section-heading'><Users size={23}/><h2>{tr('Друзья и дуэли','Friends and duels')}</h2></div><GameForm busy={game.busy} onSubmit={async()=>{if(await act('friends/request',{username:username.trim()}))setUsername('');}}><GameField label={tr('Логин тренера','Trainer username')} value={username} onChange={setUsername} maxLength={20} autoComplete='off' error={game.error?.field==='username'?gameError(game.error.code,locale):undefined}/><PendingButton busy={game.busy} disabled={username.trim().length<3} type='submit'><UserRound size={16}/>{tr('Добавить друга','Add friend')}</PendingButton></GameForm>
 {!!data.invites.length&&<div className='friend-invites'><h3>{tr('Приглашения на бой','Duel invitations')}</h3>{data.invites.map(i=><div className='friend-row' key={i.id}><div><b>{i.username}</b><span>{tr('Приглашает в приватную комнату','Invites you to a private room')} · {i.code}</span></div><div className='action-row'><PendingButton busy={game.busy} onClick={()=>void act('friends/accept-invite',{id:i.id})}>{tr('Принять вызов','Accept challenge')}</PendingButton><button className='text-button' disabled={game.busy} onClick={()=>void act('friends/decline-invite',{id:i.id})}>{tr('Отклонить','Decline')}</button></div></div>)}</div>}
 {data.friends.length?data.friends.map(f=><div className='friend-row' key={f.id}><PokemonArt id={f.avatar} name={f.username}/><div><b>{f.username}</b><span>{f.status==='accepted'?tr('В друзьях','Friend'):f.requester===p.id?tr('Заявка отправлена','Request sent'):tr('Хочет добавить вас в друзья','Sent you a friend request')}</span></div><div className='action-row'>{f.status==='accepted'?<PendingButton busy={game.busy} onClick={()=>void act('friends/invite',{id:f.id})}>{tr('Вызвать на дуэль','Challenge to duel')}</PendingButton>:f.requester!==p.id&&<PendingButton busy={game.busy} onClick={()=>void act('friends/action',{id:f.id,action:'accept'})}>{tr('Принять','Accept')}</PendingButton>}<button className='text-button' disabled={game.busy} onClick={()=>void act('friends/action',{id:f.id,action:'remove'})}>{f.status==='accepted'?tr('Убрать из друзей','Remove friend'):tr('Отменить','Dismiss')}</button></div></div>):<p className='club-empty'>{tr('Добавьте друга по игровому логину, чтобы приглашать его в приватные дуэли.','Add a friend by game username to invite them to private duels.')}</p>}</section>
 </>}
 </section>;
}
