import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {handleGame,initGameDatabase} from '../site/server/dist/server.mjs';
const dir=mkdtempSync(join(tmpdir(),'pokehabitat-sqlite-'));
process.env.AUTH_PEPPER='isolated-local-test-pepper-not-production-123456';
process.env.SITE_ORIGIN='https://game.test';
globalThis.fetch=()=>{throw new Error('External network access is forbidden in autonomous tests');};
const db=initGameDatabase(join(dir,'game.sqlite'),'site/server/migrations');
const mf={dispatchFetch:async(url,options)=>handleGame(new Request(url,options))};
let checks=0;
const check=(condition,message)=>{assert.ok(condition,message);checks++;};
try{
 const call=async(path,body,session='',origin='https://game.test')=>{
  const r=await mf.dispatchFetch(`https://game.test/api/game/${path}`,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{Origin:origin,'Content-Type':'application/json'}),...(session?{Cookie:session}:{}),'CF-Connecting-IP':'192.0.2.10'},body:body===undefined?undefined:JSON.stringify(body)});
  const data=await r.json();return {status:r.status,data,cookie:r.headers.get('Set-Cookie')||''};
 };
 const register=async(username,starter)=>{const r=await call('auth/register',{username,password:'a strong test password!',starter});check(r.status===201,`Register ${username}: ${JSON.stringify(r.data)}`);check(r.data.profile.cards.length===3,'Three starting cards');check(new Set(r.data.profile.team).size===3,'Distinct starter team');return {id:r.data.profile.id,name:username,cookie:r.cookie.split(';')[0],recovery:r.data.recoveryCode,profile:r.data.profile};};
 check((await call('me')).data.profile===null,'Anonymous profile');
 check((await call('team',{team:[1,4,7]})).status===401,'Writes require session');
 check((await call('auth/register',{username:'forged',password:'password-too-long',starter:1},'','https://evil.test')).status===403,'Cross-origin denied');
 const a=await register('trainer_alpha',1),b=await register('trainer_beta',4),c=await register('trainer_gamma',7);
 const stored=await db.prepare('SELECT password_hash,recovery_hash FROM players WHERE id=?').bind(a.id).first();
 check(stored.password_hash.startsWith('$2b$12$'),'bcrypt cost 12');check(!stored.password_hash.includes('a strong'),'No raw password');check(stored.recovery_hash!==a.recovery,'Recovery token is hashed');
 const logged=await call('auth/login',{username:a.name,password:'a strong test password!'});check(logged.status===200,'Login succeeds');check(/HttpOnly.*Secure.*SameSite=Lax/.test(logged.cookie),'Secure session attributes');
 check((await call('auth/login',{username:a.name,password:'incorrect password'})).data.error==='credentials','Generic login failure');
 const spare=JSON.parse(readFileSync('site/server/source/app/catalog.json','utf8')).find(p=>!a.profile.team.includes(p.id)&&p.stats.reduce((x,y)=>x+y,0)<400).id;
 check((await call('team',{team:[a.profile.team[0],a.profile.team[1],spare]},a.cookie)).data.error==='ownership','Unowned card denied');
 check((await call('pack',{key:crypto.randomUUID()},a.cookie)).data.error==='coins','Pack cannot overspend');
 const claimKey=crypto.randomUUID(),exp=await call('expedition',{key:claimKey,habitat:'forest'},a.cookie);
 check(exp.status===200,'Expedition grants a card');
 const repeated=await call('expedition',{key:claimKey,habitat:'forest'},a.cookie);
 check(repeated.status===200&&JSON.stringify(repeated.data.reward)===JSON.stringify(exp.data.reward),'Acquisition retries are idempotent');
 check(repeated.data.profile.credits===exp.data.profile.credits&&repeated.data.profile.cards.length===exp.data.profile.cards.length,'No repeated grant');
 check((await call('expedition',{key:crypto.randomUUID(),habitat:'water'},a.cookie)).data.error==='cooldown','Daily expedition cooldown');
 const parallel=await Promise.all([call('expedition',{key:crypto.randomUUID(),habitat:'forest'},c.cookie),call('expedition',{key:crypto.randomUUID(),habitat:'water'},c.cookie)]);
 check(parallel.filter(x=>x.status===200).length===1,'Concurrent expedition grants only once');
 await db.prepare('UPDATE players SET credits=100 WHERE id=?').bind(b.id).run();
 const packs=await Promise.all([call('pack',{key:crypto.randomUUID()},b.cookie),call('pack',{key:crypto.randomUUID()},b.cookie)]);
 check(packs.filter(x=>x.status===200).length===1,'Concurrent pack spending is atomic');
 const balance=await db.prepare('SELECT credits FROM players WHERE id=?').bind(b.id).first();check(balance.credits>=0&&balance.credits<=20,'No negative balance');
 const created=await call('arena/create',{},a.cookie);check(created.status===200&&created.data.room.status==='waiting','Create PvP room');const code=created.data.room.code;
 check((await call(`arena?code=${code}`,undefined,b.cookie)).status===403,'Room detail protected before join');
 check((await call('arena/join',{code},a.cookie)).status===409,'Cannot duel yourself');
 const joining=await Promise.all([call('arena/join',{code},b.cookie),call('arena/join',{code},c.cookie)]);
 check(joining.filter(x=>x.status===200).length===1,'One guest wins concurrent join');
 const enemy=joining[0].status===200?b:c, outsider=enemy===b?c:b;
 const guestRoom=joining.find(x=>x.status===200).data.room;
 check(guestRoom.sides.length===2&&guestRoom.sides.every(s=>s.team.length===3),'Two real teams of three');
 check(!Object.hasOwn(guestRoom,'orders'),'Opponent orders omitted');
 check((await call('arena/action',{code,action:'forfeit'},outsider.cookie)).status===403,'Outsider cannot forfeit match');
 let current=(await call(`arena?code=${code}`,undefined,a.cookie)).data.room;
 const first=await call('arena/action',{code,action:'order',round:current.round,order:{kind:'attack',index:0}},a.cookie);
 check(first.status===200&&first.data.room.ownOrder.kind==='attack','Own order confirmed');
 const masked=(await call(`arena?code=${code}`,undefined,enemy.cookie)).data.room;
 check(masked.opponentReady&&masked.ownOrder===null&&!Object.hasOwn(masked,'orders'),'Opponent choice stays private');
 const duplicate=await call('arena/action',{code,action:'order',round:current.round,order:{kind:'attack',index:1}},a.cookie);
 check(duplicate.status===200&&duplicate.data.room.version===first.data.room.version,'Submitted order cannot be overwritten');
 const resolved=await call('arena/action',{code,action:'order',round:current.round,order:{kind:'attack',index:0}},enemy.cookie);
 check(resolved.status===200&&resolved.data.room.round===2,'Round resolves after both players act');current=resolved.data.room;
 check(current.logs.some(e=>e.kind==='attack'),'Structured move log');check(current.sides.flatMap(s=>s.team).every(p=>p.hp>=0&&p.hp<=p.maxHp),'HP bounded');
 check((await call('arena/action',{code,action:'order',round:1,order:{kind:'attack',index:0}},a.cookie)).status===409,'Stale round cannot replay');
 if(current.status==='active'){
  const r=await call('arena/action',{code,action:'order',round:2,order:{kind:'attack',index:0}},a.cookie);check(r.status===200,'Second round host order');
  const r2=await call('arena/action',{code,action:'order',round:2,order:{kind:'attack',index:0}},enemy.cookie);check(r2.status===200,'Second round guest order');current=r2.data.room;
 }
 if(current.status==='active'){const end=await call('arena/action',{code,action:'forfeit'},enemy.cookie);check(end.status===200&&end.data.room.winner===a.id,'Server-controlled surrender result');current=end.data.room;}
 const records=await db.prepare('SELECT * FROM battle_rewards WHERE room_code=?').bind(code).all();check(records.results.length===2&&records.results.every(x=>x.applied===1),'Both result records applied');
 const before=JSON.stringify((await call('me',undefined,a.cookie)).data.profile);
 await call('arena/action',{code,action:'sync'},a.cookie);await call('arena/action',{code,action:'forfeit'},a.cookie);
 check(JSON.stringify((await call('me',undefined,a.cookie)).data.profile)===before,'Terminal match cannot reward twice');
 check(!(await db.prepare('SELECT * FROM player_locks WHERE room_code=?').bind(code).first()),'Terminal match releases both players');
 const another=await call('arena/create',{},a.cookie);check(another.status===200,'Can create another room');
 await db.prepare('UPDATE rooms SET updated_at=? WHERE code=?').bind(Date.now()-1300000,another.data.room.code).run();
 check((await call('arena',undefined,a.cookie)).data.room.status==='cancelled','Waiting rooms expire');
 check(!(await db.prepare('SELECT * FROM player_locks WHERE player_id=?').bind(a.id).first()),'Expiry releases player lock');
 // Trainer expansion, using the same isolated sessions and authoritative D1 state.
 let club=await call('club',undefined,a.cookie);check(club.status===200&&club.data.tasks.length===8,'Club quests and achievements loaded');
 const explore=club.data.tasks.find(t=>t.name==='explore');check(explore.done,'Expedition completes daily quest');
 const taskStart=(await call('me',undefined,a.cookie)).data.profile;
 const claimed=await call('task/claim',{id:explore.id},a.cookie);check(claimed.status===200&&claimed.data.profile.credits===taskStart.credits+20,'Eligible quest grants exact reward');
 const taskRetry=await call('task/claim',{id:explore.id},a.cookie);check(taskRetry.data.profile.credits===claimed.data.profile.credits,'Quest retry cannot double grant');
 check((await call('task/claim',{id:'achievement:veteran'},c.cookie)).status===409,'Unmet achievement denied');
 await db.prepare('UPDATE players SET credits=150 WHERE id=?').bind(a.id).run();
 await db.prepare('DELETE FROM cards WHERE player_id=? AND pokemon_id=2').bind(a.id).run();
 const evolveKey=crypto.randomUUID(),evolved=await call('evolve',{from:1,to:2,key:evolveKey},a.cookie);
 check(evolved.status===200&&evolved.data.profile.credits===0,'Evolution spends exactly 150');
 check(evolved.data.profile.cards.some(x=>x.id===1)&&evolved.data.profile.cards.some(x=>x.id===2),'Evolution keeps original and adds new form');
 const evoRetry=await call('evolve',{from:1,to:2,key:evolveKey},a.cookie);check(evoRetry.status===200&&evoRetry.data.profile.credits===0&&evoRetry.data.profile.trainer.evolutions===1,'Evolution retry works after spending and ownership change');
 check((await call('evolve',{from:2,to:3,key:evolveKey},a.cookie)).status===400,'Evolution key cannot be reused for another edge');
 check((await call('evolve',{from:1,to:3,key:crypto.randomUUID()},a.cookie)).status===400,'Evolution must follow direct edge');
 check((await call('evolve',{from:2,to:3,key:crypto.randomUUID()},a.cookie)).data.error==='evolveCoins','Evolution cannot overspend');
 await db.prepare('UPDATE players SET credits=150 WHERE id=?').bind(a.id).run();
 const parallelEvo=await Promise.all([call('evolve',{from:2,to:3,key:crypto.randomUUID()},a.cookie),call('evolve',{from:2,to:3,key:crypto.randomUUID()},a.cookie)]);check(parallelEvo.filter(r=>r.status===200).length===1,'Concurrent evolutions spend once');
 check((await call('me',undefined,a.cookie)).data.profile.credits===0,'Concurrent evolution never overspends');
 const custom=await call('trainer',{avatar:2,cover:'water',favorites:[1,2]},a.cookie);check(custom.status===200&&custom.data.profile.trainer.cover==='water'&&custom.data.profile.trainer.favorites.length===2,'Owned trainer appearance persists');
 check((await call('trainer',{avatar:99999,cover:'water',favorites:[]},a.cookie)).status===400,'Unowned avatar rejected');
 check((await call('trainer',{avatar:2,cover:'water',favorites:[1,1]},a.cookie)).status===400,'Duplicate favorites rejected');
 check((await call('friends/request',{username:a.name},a.cookie)).status===400,'Self friendship rejected');
 check((await call('friends/request',{username:b.name},a.cookie)).status===200,'Friend request sent');
 check((await call('friends/action',{id:b.id,action:'accept'},a.cookie)).status===400,'Requester cannot accept own request');
 check((await call('friends/action',{id:a.id,action:'accept'},b.cookie)).status===200,'Receiver accepts request');
 const invitation=await call('friends/invite',{id:b.id},a.cookie);check(invitation.status===200&&invitation.data.room.inviteOnly===b.id,'Private duel created for intended friend');
 const inviteRetry=await call('friends/invite',{id:b.id},a.cookie);check(inviteRetry.status===200&&inviteRetry.data.room.code===invitation.data.room.code,'Private invite retry reuses room');
 check(!(await call('arena',undefined,c.cookie)).data.rooms.some(x=>x.code===invitation.data.room.code),'Private duel absent from public rooms');
 check((await call('arena/join',{code:invitation.data.room.code},c.cookie)).status===403,'Wrong player cannot join private duel');
 club=await call('club',undefined,b.cookie);const invite=club.data.invites[0];check(invite&&invite.code===invitation.data.room.code,'Friend sees incoming invitation');
 check((await call('friends/accept-invite',{id:invite.id},c.cookie)).status===409,'Only receiver can accept invitation');
 const privateJoined=await call('friends/accept-invite',{id:invite.id},b.cookie);check(privateJoined.status===200&&privateJoined.data.room.status==='active','Friend joins invited duel');
 check((await call('friends/accept-invite',{id:invite.id},b.cookie)).status===200,'Accepted invitation retry returns existing room');
 await call('arena/action',{code:invitation.data.room.code,action:'forfeit'},b.cookie);
 check((await call('arena/practice',{difficulty:'impossible'},c.cookie)).status===400,'Unknown bot difficulty rejected');
 const botProfile=(await call('me',undefined,c.cookie)).data.profile;
 const ratingBeforeBots=(await call('ranking',undefined,a.cookie)).data.players;
 for(const difficulty of ['easy','normal','hard']){
  const practice=await call('arena/practice',{difficulty},c.cookie);check(practice.status===200&&practice.data.room.practice===difficulty&&practice.data.room.sides[1].id==='practice-bot','Explicit bot room '+difficulty);
  const r=await call('arena/action',{code:practice.data.room.code,action:'order',round:1,order:{kind:'attack',index:0}},c.cookie);check(r.status===200&&(r.data.room.round===2||r.data.room.status==='finished'),'Server bot resolves simultaneous round '+difficulty);
  if(r.data.room.status==='active')await call('arena/action',{code:practice.data.room.code,action:'forfeit'},c.cookie);
  const finished=(await call('me',undefined,c.cookie)).data.profile;
  const xp=finished.trainer.xp;await call('arena/action',{code:practice.data.room.code,action:'sync'},c.cookie);
  check((await call('me',undefined,c.cookie)).data.profile.trainer.xp===xp,'Practice reward applied once');
 }
 const winPractice=await call('arena/practice',{difficulty:'easy'},c.cookie);
 const winRow=await db.prepare('SELECT state FROM rooms WHERE code=?').bind(winPractice.data.room.code).first();const winState=JSON.parse(winRow.state);
 winState.sides[1].team.forEach(f=>f.hp=0);winState.sides[1].team[winState.sides[1].active].hp=1;
 winState.sides[1].team.forEach(f=>f.hp=0);
 await db.prepare('UPDATE rooms SET state=? WHERE code=?').bind(JSON.stringify(winState),winPractice.data.room.code).run();
 const winRound=await call('arena/action',{code:winPractice.data.room.code,action:'order',round:1,order:{kind:'attack',index:0}},c.cookie);
 check(winRound.status===200&&winRound.data.room.winner===c.id,'Practice win resolved by server engine');
 check((await call('club',undefined,c.cookie)).data.tasks.find(t=>t.name==='practice').done,'Practice win completes daily task');
 const afterBot=(await call('me',undefined,c.cookie)).data.profile;
 check(afterBot.wins===botProfile.wins&&afterBot.losses===botProfile.losses&&afterBot.credits===botProfile.credits,'Practice leaves PvP records and coins unchanged');
 check(afterBot.trainer.xp>=botProfile.trainer.xp+15,'Practice completion earns trainer XP');
 // Either beta or gamma can win the earlier concurrent PvP join. Practice
 // must leave the existing PvP ranking unchanged for every player.
 const rating=await call('ranking',undefined,a.cookie);check(rating.status===200&&JSON.stringify(rating.data.players)===JSON.stringify(ratingBeforeBots),'Rating excludes bot matches');
 const previous=new Date();previous.setUTCMonth(previous.getUTCMonth()-1);previous.setUTCDate(10);const previousDay=Math.floor(previous.getTime()/86400000);
 await db.prepare('UPDATE battle_rewards SET day=? WHERE player_id=?').bind(previousDay,a.id).run();
 const season=await call('season/claim',{},a.cookie);check(season.status===200,'Previous closed season leader can claim reward');
 const seasonRetry=await call('season/claim',{},a.cookie);check(seasonRetry.data.profile.credits===season.data.profile.credits,'Season reward claimed once');
 const reset=await call('auth/recover',{username:a.name,password:'a replacement password!',recoveryCode:a.recovery});check(reset.status===200&&reset.data.recoveryCode!==a.recovery,'Recovery rotates secret');
 check((await call('me',undefined,a.cookie)).data.profile===null,'Recovery revokes old session');
 check((await call('auth/login',{username:a.name,password:'a strong test password!'})).status===401,'Old password invalidated');
 check((await call('auth/recover',{username:a.name,password:'another replacement!',recoveryCode:a.recovery})).status===401,'Old recovery code cannot replay');
 const newLogin=await call('auth/login',{username:a.name,password:'a replacement password!'});check(newLogin.status===200,'Recovered password works');
 await call('auth/logout',{},newLogin.cookie.split(';')[0]);check((await call('me',undefined,newLogin.cookie.split(';')[0])).data.profile===null,'Logout revokes session');
 const persisted=(await call('me',undefined,c.cookie)).data.profile;
 db.sqlite.close();const reopened=initGameDatabase(join(dir,'game.sqlite'),'site/server/migrations');
 check(JSON.stringify((await call('me',undefined,c.cookie)).data.profile)===JSON.stringify(persisted),'Sessions and all player progress survive database restart');
 check(reopened.sqlite.prepare('PRAGMA integrity_check').get().integrity_check==='ok','SQLite integrity after concurrent operations');
 reopened.sqlite.close();
 console.log(JSON.stringify({suite:'game integration',checks,status:'passed',runtime:'Node + local SQLite, no external network',multiplayer:'three isolated sessions'}));
}finally{try{db.sqlite.close();}catch{}rmSync(dir,{recursive:true,force:true});}
