"use client";
import {useEffect,useRef,useState,type CSSProperties} from "react";
import {Leaf,Mountain,Waves,Trees,Sparkles,Globe2,CircleDot,X,Play,HeartPulse,Swords,Gauge,ChevronDown,CircleHelp,Building2,Gem,Zap,LoaderCircle} from "lucide-react";
import {Dialog,DialogClose,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {pokemon,byId,type Pokemon,type Move} from "../lib/pokemon";
import {PokemonArt,TypeBadge,types} from "../components/pokemon-visuals";
import {MoveEffect} from "../components/move-effect";
import {GameHub} from "../components/game-hub";
import {PresenceCounter} from "../components/presence-counter";
import {useGame} from "../lib/game-client";
import {useAtlasQuery,useMainView,useHabitat,useSiteLocale,setSiteLocale,notifyNavigation} from "../lib/route-state";
const habitats=[{id:"all",ru:"Все среды",en:"All habitats",icon:CircleDot},{id:"forest",ru:"Леса",en:"Forests",icon:Trees},{id:"water",ru:"Водоёмы",en:"Waters",icon:Waves},{id:"mountain",ru:"Горы",en:"Mountains",icon:Mountain},{id:"grassland",ru:"Луга",en:"Grasslands",icon:Leaf},{id:"cave",ru:"Пещеры",en:"Caves",icon:Gem},{id:"urban",ru:"Города",en:"Cities",icon:Building2},{id:"unknown",ru:"Особая среда",en:"Unclassified",icon:Sparkles}];
const copy={
ru:{club:"Клуб любителей покемонов",kicker:"ИССЛЕДУЙ, УЗНАВАЙ, ВДОХНОВЛЯЙСЯ",title:"У каждого своя стихия",subtitle:"Знакомься с покемонами и миром, в котором они живут.",featured:"БЛИЖЕ К ПРИРОДЕ",open:"Открыть карточку",atlas:"Атлас покемонов",habitats:"Среды обитания",more:"Показать ещё",shown:"Показано",of:"из",overview:"Обзор",evolution:"Эволюция",attacks:"Атаки",stats:"Характеристики",height:"Рост",weight:"Вес",m:"м",kg:"кг",abilities:"Способности",hidden:"Скрытая",close:"Закрыть карточку",hp:"Здоровье",attack:"Сила",defense:"Защита",spatk:"Сп. атака",spdef:"Сп. защита",speed:"Скорость",total:"Сумма",base:"Базовые показатели игры. Уровень, характер и тренировки меняют реальные значения.",power:"Мощность",accuracy:"Точность",play:"Применить",playing:"Применение…",animation:"Стилизованная демонстрация атак",noEvo:"У этого покемона нет известных эволюций.",evoHint:"Условия для основной формы. В разных играх они могут отличаться.",noData:"Редкие виды и покемоны без классифицированной среды обитания.",agility:"Ловкость",agilityHint:"Индекс ловкости = базовая скорость ÷ 255 × 100. Показатель атласа, а не отдельная характеристика игры.",footer:"Для тех, кто любит исследовать.",rights:"Pokémon © Nintendo, Creatures, GAME FREAK.",source:"Данные и изображения: PokéAPI",empty:"В этой среде пока нет покемонов.",reset:"Все среды"},
en:{club:"The Pokémon lovers’ club",kicker:"EXPLORE, DISCOVER, BE INSPIRED",title:"Everyone has an element",subtitle:"Meet the Pokémon and the world they call home.",featured:"CLOSER TO NATURE",open:"Explore Pokémon",atlas:"The Pokémon atlas",habitats:"Natural habitats",more:"Load more",shown:"Showing",of:"of",overview:"Overview",evolution:"Evolution",attacks:"Moves",stats:"Base stats",height:"Height",weight:"Weight",m:"m",kg:"kg",abilities:"Abilities",hidden:"Hidden",close:"Close Pokémon details",hp:"HP",attack:"Attack",defense:"Defense",spatk:"Sp. attack",spdef:"Sp. defense",speed:"Speed",total:"Total",base:"Base game stats. Level, nature and training affect actual values.",power:"Power",accuracy:"Accuracy",play:"Use move",playing:"Using move…",animation:"Stylized move demonstration",noEvo:"This Pokémon has no known evolutions.",evoHint:"Conditions apply to the standard form and may vary between games.",noData:"Rare species and Pokémon without a classified natural habitat.",agility:"Agility",agilityHint:"Agility index = base Speed ÷ 255 × 100. An atlas indicator, not a separate game stat.",footer:"For curious explorers.",rights:"Pokémon © Nintendo, Creatures, GAME FREAK.",source:"Data and artwork: PokéAPI",empty:"There are no Pokémon in this habitat yet.",reset:"All habitats"}};
export default function Home(){
 const game=useGame();const view=useMainView();
 useEffect(()=>{document.documentElement.removeAttribute("data-theme");},[]);
 const params=new URLSearchParams(useAtlasQuery()),query=params.get("q")||"",type=params.get("type")||"",sort=params.get("sort")||"number",minimum=Number(params.get("min"))||0;
 const filterChange=(key:string,value:string)=>{const u=new URL(window.location.href);if(value)u.searchParams.set(key,value);else u.searchParams.delete(key);window.history.replaceState(null,"",u);notifyNavigation();setLimit(12);};
 const resetFilters=()=>{const u=new URL(window.location.href);["q","type","sort","min"].forEach(k=>u.searchParams.delete(k));window.history.replaceState(null,"",u);notifyNavigation();setLimit(12);};
 const unsaved=useRef(false),[pendingView,setPendingView]=useState<string|null>(null);
 useEffect(()=>{const listen=(e:Event)=>{unsaved.current=(e as CustomEvent<boolean>).detail;};window.addEventListener("pokehabitat:dirty",listen);return()=>window.removeEventListener("pokehabitat:dirty",listen);},[]);
 const navigate=(v:string)=>{const u=new URL(window.location.href);if(v==="atlas")u.searchParams.delete("view");else u.searchParams.set("view",v);window.history.pushState(null,"",u);notifyNavigation();game.clearError();requestAnimationFrame(()=>document.getElementById("main-content")?.focus());};
 const changeView=(v:string)=>{if(unsaved.current&&v!==view){setPendingView(v);return;}navigate(v);};
 const locale=useSiteLocale(),habitat=useHabitat();const [limit,setLimit]=useState(12),[selected,setSelected]=useState<Pokemon>(pokemon.find(p=>p.id===25)||pokemon[0]),[open,setOpen]=useState(false),[detailTab,setDetailTab]=useState("overview"),[activeMove,setActiveMove]=useState<Move|null>(null);const lastTrigger=useRef<HTMLButtonElement|null>(null);const stage=useRef<HTMLDivElement|null>(null);const c=copy[locale];
 useEffect(()=>{document.documentElement.lang=locale;document.title=locale==="ru"?"PokéHabitat — Клуб любителей покемонов":"PokéHabitat — The Pokémon lovers’ club"},[locale]);
 useEffect(()=>{const reset=()=>setLimit(12);window.addEventListener("popstate",reset);return()=>window.removeEventListener("popstate",reset);},[]);
 const changeHabitat=(value:string)=>{setLimit(12);const url=new URL(window.location.href);if(value==="all")url.searchParams.delete("habitat");else url.searchParams.set("habitat",value);window.history.replaceState(null,"",url);notifyNavigation();};
 const playMove=(move:Move)=>{setActiveMove(move);if(window.matchMedia("(max-width: 680px)").matches)stage.current?.scrollIntoView({block:"start",behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"})};
 const changeLocale=setSiteLocale;
 const filtered=pokemon.filter(p=>(habitat==="all"||p.habitat===habitat)&&(!type||p.types.includes(type))&&p.stats.reduce((a,b)=>a+b,0)>=minimum&&(!query||`${p.name.ru} ${p.name.en} ${p.id}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))).sort((a,b)=>sort==="power"?b.stats.reduce((x,y)=>x+y,0)-a.stats.reduce((x,y)=>x+y,0):sort==="speed"?b.stats[5]-a.stats[5]:sort==="name"?a.name[locale].localeCompare(b.name[locale]):a.id-b.id),featured=habitat==="all"?pokemon.find(p=>p.id===25):filtered[0];
 const showPokemon=(p:Pokemon,trigger:HTMLButtonElement)=>{lastTrigger.current=trigger;setSelected(p);setDetailTab("overview");setActiveMove(null);setOpen(true)};
 const selectEvolution=(id:number)=>{const p=byId.get(id);if(!p)return;setSelected(p);setActiveMove(null);if(window.matchMedia("(max-width: 680px)").matches)stage.current?.scrollIntoView({block:"start",behavior:"auto"});};
 const statLabels=[c.hp,c.attack,c.defense,c.spatk,c.spdef,c.speed];
 return <><AlertDialog open={pendingView!==null} onOpenChange={v=>{if(!v)setPendingView(null);}}><AlertDialogContent className="game-confirm"><AlertDialogTitle>{locale==="ru"?"Не сохранены изменения профиля":"Unsaved profile changes"}</AlertDialogTitle><AlertDialogDescription>{locale==="ru"?"При переходе в другой раздел изменения оформления будут потеряны.":"Leaving this section will discard your appearance changes."}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>{locale==="ru"?"Остаться":"Stay"}</AlertDialogCancel><AlertDialogAction onClick={()=>{if(pendingView){unsaved.current=false;navigate(pendingView);setPendingView(null);}}}>{locale==="ru"?"Перейти без сохранения":"Discard and leave"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><a href="#main-content" className="skip-link">{locale==="ru"?"Перейти к содержимому":"Skip to main content"}</a><div className="nature-background" data-habitat={habitat==="all"?"forest":habitat} aria-hidden="true"/><div className="site-wrap">
 <header className="header glass"><button onClick={()=>changeView("atlas")} className="brand" aria-label="PokéHabitat"><span className="brand-mark"><CircleDot size={24} strokeWidth={1.7} aria-hidden="true"/></span><span>poké<span className="brand-light">habitat</span></span></button><span className="club-label">{c.club}</span><PresenceCounter locale={locale}/><div className="language-control"><Globe2 size={17} aria-hidden="true"/><div className="language-options" role="group" aria-label={locale==="ru"?"Язык сайта":"Site language"}><button onClick={()=>changeLocale("ru")} aria-pressed={locale==="ru"} lang="ru">RU</button><button onClick={()=>changeLocale("en")} aria-pressed={locale==="en"} lang="en">EN</button></div></div></header>
 <nav className="game-nav glass" aria-label={locale==="ru"?"Разделы клуба":"Club sections"}>{[["atlas","Атлас","Atlas"],["collection","Мои карточки","My cards"],["arena","Арена","Arena"],["club","Клуб","Club"],["account","Кабинет","Account"]].map(([id,ru,en])=><button key={id} aria-current={view===id?"page":undefined} onClick={()=>changeView(id)}>{locale==="ru"?ru:en}</button>)}{game.profile&&<span className="nav-player">{game.profile.username}<b>{game.profile.credits} {locale==="ru"?"монет":"coins"}</b></span>}</nav>
 <main id="main-content" tabIndex={-1}><GameHub mode={view} locale={locale} game={game} onNav={changeView} onPreview={(id,trigger)=>{const p=byId.get(id);if(p)showPokemon(p,trigger);}}/>{view==="atlas"&&<><section className="intro" aria-labelledby="page-title"><div className="intro-copy"><span className="eyebrow">{c.kicker}</span><h1 id="page-title">{c.title}</h1><p>{c.subtitle}</p><span className="collection-count"><CircleDot size={16} aria-hidden="true"/>{pokemon.length} {locale==="ru"?"покемонов":"Pokémon"}<span className="separator">·</span>{habitats.length-1} {locale==="ru"?"сред обитания":"habitats"}</span></div>{featured&&<button className="featured-card glass" onClick={e=>showPokemon(featured,e.currentTarget)} style={{"--pokemon-color":types[featured.types[0]]?.color} as CSSProperties}><div className="featured-info"><span className="micro-label">{c.featured}</span><div className="featured-name">{featured.name[locale]}</div><div className="badge-row">{featured.types.map(t=><TypeBadge key={t} type={t} locale={locale}/>)}</div><span className="featured-action">{c.open}<span className="small-play"><Play size={12} fill="currentColor" aria-hidden="true"/></span></span></div><PokemonArt id={featured.id} name={featured.name[locale]} className="featured-art" priority/></button>}</section>
 <section id="atlas" className="atlas" aria-labelledby="atlas-title"><div className="atlas-heading"><h2 id="atlas-title">{c.atlas}<span className="count-pill">{pokemon.length}</span></h2><span className="habitat-caption"><Leaf size={15} aria-hidden="true"/>{c.habitats}</span></div><div className="habitat-nav glass" role="group" aria-label={c.habitats}>{habitats.map(h=>{const Icon=h.icon;return <button key={h.id} onClick={()=>changeHabitat(h.id)} aria-pressed={habitat===h.id} className={habitat===h.id?"habitat-active":""}><Icon size={18} aria-hidden="true"/><span>{h[locale]}</span>{habitat===h.id&&<span className="habitat-count">{filtered.length}</span>}</button>})}</div>
 <div className="atlas-filters glass"><label>{locale==="ru"?"Поиск по имени или номеру":"Name or number"}<input type="search" value={query} onChange={e=>filterChange("q",e.target.value)} placeholder={locale==="ru"?"Например, Пикачу":"For example, Pikachu"}/></label><label>{locale==="ru"?"Тип":"Type"}<select value={type} onChange={e=>filterChange("type",e.target.value)}><option value="">{locale==="ru"?"Любой тип":"Any type"}</option>{Object.entries(types).map(([id,t])=><option key={id} value={id}>{t.name[locale]}</option>)}</select></label><label>{locale==="ru"?"Сумма характеристик":"Total base stats"}<select value={minimum} onChange={e=>filterChange("min",e.target.value)}>{[0,300,400,500,600].map(n=><option key={n} value={n}>{n?`${n}+`:locale==="ru"?"Любая":"Any"}</option>)}</select></label><label>{locale==="ru"?"Сортировка":"Sort by"}<select value={sort} onChange={e=>filterChange("sort",e.target.value)}>{[["number","Номер","Number"],["name","Имя","Name"],["power","Сила (сумма)","Total stats"],["speed","Скорость","Speed"]].map(([id,ru,en])=><option key={id} value={id}>{locale==="ru"?ru:en}</option>)}</select></label>{(query||type||minimum||sort!=="number")&&<button className="text-button" onClick={resetFilters}>{locale==="ru"?"Сбросить":"Reset"}</button>}</div>
 <div className="pokemon-grid">{filtered.slice(0,limit).map((p,i)=><button className="pokemon-card glass" key={p.id} onClick={e=>showPokemon(p,e.currentTarget)} aria-label={`${c.open}: ${p.name[locale]}`} style={{"--pokemon-color":types[p.types[0]]?.color,"--card-index":i%12} as CSSProperties}><div className="card-top"><span className="pokedex-number">#{String(p.id).padStart(3,"0")}</span><span className="habitat-mini">{habitats.find(h=>h.id===p.habitat)?.[locale]}</span></div><div className="card-art-wrap"><div className="art-halo" aria-hidden="true"/><PokemonArt id={p.id} name={p.name[locale]} className="card-art" priority={i<4}/></div><div className="card-info"><h3>{p.name[locale]}</h3><span className="pokemon-genus">{p.genus[locale]}</span><div className="badge-row">{p.types.map(t=><TypeBadge key={t} type={t} locale={locale}/>)}</div></div><div className="card-stats"><span><HeartPulse size={15} aria-hidden="true"/><span>HP<b>{p.stats[0]}</b></span></span><span><Swords size={15} aria-hidden="true"/><span>{c.attack}<b>{p.stats[1]}</b></span></span><span><Gauge size={15} aria-hidden="true"/><span>{locale==="ru"?"Скор.":"Speed"}<b>{p.stats[5]}</b></span></span></div></button>)}</div>
 {!filtered.length&&<div className="empty-state glass"><CircleHelp size={30}/><p>{locale==="ru"?"По выбранным условиям покемоны не найдены.":"No Pokémon match your filters."}</p><button className="solid-button" onClick={()=>{resetFilters();changeHabitat("all");}}>{locale==="ru"?"Сбросить фильтры":"Reset filters"}</button></div>}<div className="collection-bottom"><p role="status">{c.shown} {Math.min(limit,filtered.length)} {c.of} {filtered.length}</p>{limit<filtered.length&&<button className="more-button glass" onClick={()=>setLimit(l=>l+12)}>{c.more}<ChevronDown size={18} aria-hidden="true"/></button>}</div></section></>}</main>
 <footer><div className="footer-brand"><CircleDot size={19} aria-hidden="true"/><span>pokéhabitat</span><p>{c.footer}</p></div><div className="credits"><a href="https://pokeapi.co/" target="_blank" rel="noreferrer">{c.source}</a><span>{c.rights}</span></div></footer></div>
 <Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v)setActiveMove(null)}}>{selected&&<DialogContent className="detail-dialog" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();lastTrigger.current?.focus()}}><DialogClose asChild><button className="close-button" aria-label={c.close} onClick={()=>{setOpen(false);setActiveMove(null)}}><X size={22}/></button></DialogClose><div className="detail-layout" style={{"--pokemon-color":types[selected.types[0]]?.color} as CSSProperties}>
 <div ref={stage} className={`detail-stage ${activeMove?"is-attacking":""}`}><span className="detail-number">#{String(selected.id).padStart(3,"0")}</span><div className="stage-rings" aria-hidden="true"/><PokemonArt key={selected.id} id={selected.id} name={selected.name[locale]} className="detail-art evolution-flash" priority/><MoveEffect move={activeMove} onComplete={()=>setActiveMove(null)}/><div className="stage-label" role="status">{activeMove?<><Zap size={15} aria-hidden="true"/>{activeMove.name[locale]}</>:<><Leaf size={15} aria-hidden="true"/>{habitats.find(h=>h.id===selected.habitat)?.[locale]}</>}</div><div className="physical-stats"><span>{c.height}<b>{new Intl.NumberFormat(locale,{maximumFractionDigits:1}).format(selected.height)} <small>{c.m}</small></b></span><span>{c.weight}<b>{new Intl.NumberFormat(locale,{maximumFractionDigits:1}).format(selected.weight)} <small>{c.kg}</small></b></span></div>{detailTab==="attacks"&&<span className="animation-caption">{c.animation}</span>}</div>
 <div className="detail-info"><div className="detail-head"><span className="pokemon-genus">{selected.genus[locale]}</span><DialogTitle className="detail-name">{selected.name[locale]}</DialogTitle><div className="badge-row">{selected.types.map(t=><TypeBadge key={t} type={t} locale={locale}/>)}</div><DialogDescription className="detail-description">{selected.description[locale]}</DialogDescription></div><Tabs value={detailTab} onValueChange={v=>{setDetailTab(v);setActiveMove(null)}} className="detail-tabs"><TabsList className="detail-tab-list" aria-label={locale==="ru"?"Информация о покемоне":"Pokémon information"}><TabsTrigger value="overview">{c.overview}</TabsTrigger><TabsTrigger value="evolution">{c.evolution}</TabsTrigger><TabsTrigger value="attacks">{c.attacks}</TabsTrigger><TabsTrigger value="stats">{c.stats}</TabsTrigger></TabsList>
 <TabsContent value="overview" className="detail-tab-content"><h3>{c.abilities}</h3><div className="ability-list">{selected.abilities.map(a=><div className="ability-card" key={a.name.en}><span className="ability-icon"><Sparkles size={18}/></span><div><h4>{a.name[locale]}{a.hidden&&<span className="hidden-label">{c.hidden}</span>}</h4><p>{a.description[locale]}</p></div></div>)}</div>{selected.habitat==="unknown"&&<p className="detail-note">{c.noData}</p>}</TabsContent>
 <TabsContent value="evolution" className="detail-tab-content"><h3>{c.evolution}</h3>{selected.evolution.edges.length===0?<p className="detail-note">{c.noEvo}</p>:<div className="evolution-list">{selected.evolution.edges.map(edge=>{const from=selected.evolution.nodes.find(n=>n.id===edge.from)!,to=selected.evolution.nodes.find(n=>n.id===edge.to)!;return <div className="evolution-pair" key={`${edge.from}-${edge.to}`}><button type="button" className={`evolution-node ${from.id===selected.id?"current-evolution":""}`} aria-pressed={from.id===selected.id} onClick={()=>selectEvolution(from.id)}><PokemonArt id={from.id} name={from.name[locale]}/><span>{from.name[locale]}</span></button><div className="evolution-condition"><span className="evolution-connector" aria-hidden="true"/><span>{edge.condition[locale]}</span></div><button type="button" className={`evolution-node ${to.id===selected.id?"current-evolution":""}`} aria-pressed={to.id===selected.id} onClick={()=>selectEvolution(to.id)}><PokemonArt id={to.id} name={to.name[locale]}/><span>{to.name[locale]}</span></button></div>})}</div>}<p className="detail-note">{c.evoHint}</p></TabsContent>
 <TabsContent value="attacks" className="detail-tab-content"><h3>{c.attacks}</h3><div className="moves-list">{selected.moves.map(move=><div className="move-card" key={move.id}><div className="move-title"><h4>{move.name[locale]}</h4><TypeBadge type={move.type} locale={locale}/></div><p>{move.description[locale]}</p><div className="move-bottom"><div className="move-numbers"><span>{c.power}<b>{move.power??"—"}</b></span><span>{c.accuracy}<b>{move.accuracy===null?"—":`${move.accuracy}%`}</b></span></div><button className="solid-button" disabled={!!activeMove} onClick={()=>playMove(move)}>{activeMove?.id===move.id?<LoaderCircle size={15} className="spinner" aria-hidden="true"/>:<Play size={14} fill="currentColor" aria-hidden="true"/>}{activeMove?.id===move.id?c.playing:c.play}</button></div></div>)}</div></TabsContent>
 <TabsContent value="stats" className="detail-tab-content"><div className="stats-header"><h3>{c.stats}</h3><span>{c.total}<b>{selected.stats.reduce((a,b)=>a+b,0)}</b></span></div><div className="stat-bars">{selected.stats.map((v,i)=><div className="stat-bar-row" key={i}><span>{statLabels[i]}</span><div className="stat-track"><span style={{width:`${v/255*100}%`}}/></div><b>{v}</b></div>)}</div><div className="agility-index"><Gauge size={18} aria-hidden="true"/><span>{c.agility}</span><b>{Math.round(selected.stats[5]/255*100)}<small>/100</small></b></div><p className="detail-note">{c.agilityHint}</p><p className="detail-note">{c.base}</p></TabsContent>
 </Tabs></div></div></DialogContent>}</Dialog></>;
}
